### ISSUE TITLE
Codemod contribution suggestion: Remove type-annotations from code

### ISSUE THREAD

**Issue by aran3** [Instagram/LibCST#1022]
I wrote a codemod that removes type annotations (PEP 484 and PEP 526) from code.
Would it be a good idea to contribute this into this repository?

## Documentation from my code:

    This is meant to be used on a codebase that contains Type Annotations (PEP 484),
    for users who do not want to use these annotations for a static type analyzer
    (such as mypy), and find the annotations distracting or verbose.
    The assumption is that these type annotations have no runtime effect, with
    exceptions which are known to DO have runtime effects and will therefore be
    preserved.
    This will not work for other uses that require that type annotations be
    available at runtime (such as for Pydantic, SQLAlchemy, and other libraries).

    The following behaviors are implemented:
    * All function parameters' type annotations will be removed
    * Functions return type will be removed
    * Variables type annotations (PEP 526) which do not include an assignment will
      be kept as-is. Eg `x: int` will be kept.
    * Variables type annotations which include an assignment will be
      replaced with assignment only. Eg `x: int = 5` -> `x = 5`.
      * Unless they are defined inside a `dataclass` definition
      * Or defined inside an `attr.s` / `attrs.define` class definition
      * Or inside a `NamedTuple` or `TypedDict` derived class definition

**Comment by aran3** [comment]
I would appreciate any response here - I want to contribute this, but need to seek approval from my company as well as do some extra work to make fit as a built-in codemod, and so want to get a "go-ahead" before I work on this and submit a PR.

**Comment by zsol** [comment]
Hey, sorry for taking so long to respond. This codemod would not be used within Meta, so it's unlikely I'll have the time to maintain it, especially given typing related syntax is likely to evolve in the future.
