### ISSUE TITLE
Binder/IPython (Notebook) interactive online tutorial does not start

### ISSUE THREAD

**Issue by AlbertMietus** [Instagram/LibCST#1054]
On  ReadTheDoc page https://libcst.readthedocs.io/en/latest/tutorial.html (Parsing and Visiting) a (link to) a interactive online tutorial is provides (which is nic) However: **It does not start**

| _Failed to build libcst_
|  _ERROR: Could not build wheels for libcst, which is required to install pyproject.toml-based projects_

Partial related: #450

**Comment by zsol** [comment]
I believe this is fixed now with #1083. Thanks for reporting
