### ISSUE TITLE
Type annotation in leave function makes it impossible to inject complex nodes

### ISSUE THREAD

**Issue by fus-kus** [Instagram/LibCST#1055]
I am working on a script where I need to inject a secondary tree in place of a comment with a specific message. 
overwriting the `leave_EmptyLine` function, and substituting the node for what i need works. The issue arises with mypy, because the type annotation for the  `leave_EmptyLine` as well as `on_leave` is structured in such a way that i cannot return a general CSTNode, but it needs to be of the same type as `original_node` which defeats the purpose.

Would it be possible to extend the typing system to allow the return of a general CSTNode?

**Comment by zsol** [comment]
This limitation is on purpose. Allowing to change an EmptyLine node to an arbitrary CSTNode is very likely to cause an incorrect CST. If you find yourself needing to do this, I'd recommend trying to find the parent of the interesting `EmptyLine` node and make your changes to that node instead (IIRC most nodes that own `EmptyLine` have other fields that allow statements)
