### ISSUE TITLE
ParseSyntaxError with raw string in combination with backslash and new line

### ISSUE THREAD

**Issue by smorokin** [Instagram/LibCST#1062]
The following minimal example leads to a ParseSyntaxError:
```python
from libcst.native import parse_expression

s = r"text\
more text"

print(s)  # works

parse_expression(s)  # raises ParserSyntaxError
```
The details of the error are:
```
Syntax Error @ 2:1.
parser error: error at 2:5: expected one of !=, %, &, (, *, **, +, ,, -, ., /, //, <, <<, <=, ==, >, >=, >>, @, NEWLINE, [, ^, and, if, in, is, not, or, |

more text
^
```

**Comment by p21nc3** [comment]
> The following minimal example leads to a ParseSyntaxError:
> 
> ```python
> from libcst.native import parse_expression
> 
> s = r"text\
> more text"
> 
> print(s)  # works
> 
> parse_expression(s)  # raises ParserSyntaxError
> ```
> 
> The details of the error are:
> 
> ```
> Syntax Error @ 2:1.
> parser error: error at 2:5: expected one of !=, %, &, (, *, **, +, ,, -, ., /, //, <, <<, <=, ==, >, >=, >>, @, NEWLINE, [, ^, and, if, in, is, not, or, |
> 
> more text
> ^
> ```

Hi @smorokin, looks like the parsesyntaxerror is due to the combination of a raw string with a backslash and a space. I suggest adding up an extra backslash like this 👇
```
s = r"text\\ more text"
```
The extra backslash will help escape the backslash itself in the string, preventing it from causing a syntax error during parsing.

**Comment by smorokin** [comment]
Hi @p21nc3 , thanks for your reply, but the backslash in the original string `s` is not printed. If you do the print you will see that the string contains a new line and no `\`.

**Comment by p21nc3** [comment]
Hi @smorokin, then will it make sense to remove the backslash. Like this
```
from libcst.native import parse_expression
s = r"text more text"  
print(s)  
parse_expression(s)  # should not raise ParseSyntaxError
```

**Comment by zsol** [comment]
This is expected.

```
text\
more text
```
is not a valid python program, `ast.parse()` also raises a `SyntaxError`

**Comment by smorokin** [comment]
Hi @zsol ! The string in the example is valid python. The print works just fine. You can check for yourself by running this :
```python
s = r"text\
more text"
print(s)  # works
```

But I can understand if you don't want to fix this edge case.

**Comment by zsol** [comment]
Printing a string doesn't prove that it's valid python; this also works:
```
s = "#$#*&$*&#$^&*($&^#&*$"
print(s)
```

However, try:
```
s = r"text\
more text"
import ast
ast.parse(s)
```

**Comment by smorokin** [comment]
You are not understanding what I mean. Of course the content of the string is invalid python. Try parsing the whole snippet like you would parse a python file. To use your example:
```python
ast.parse('s = "#$#*&$*&#$^&*($&^#&*$" ')
``` 
This will work just fine.

**Comment by zsol** [comment]
You're right, I'm not sure what you mean. Can you give me a snippet that fails to execute? Or, even better - a failing test case. I'm happy to fix it.

(Note that `s = "blah"` is _not_ an expression, so `parse_expression` should fail on it - but `parse` works)

**Comment by smorokin** [comment]
Yeah, that's my bad for simplifying my problem wrong. Ok, the issue is that the library can't parse a file containing a string with a line continuation backslash, so parsing the following fails:
```python
s = r"text \
more text"
print(s)  # works
```

**Comment by smorokin** [comment]
But as I said it is not so important.
