### ISSUE TITLE
Add a `with_deep_changes` to make change deep attribute of Literal/Sequence value easier.

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#107]
We have useful helpers to generate an immutable updated node: `.with_changes(**changes)` and `.deep_repalce(old_node: CSTNode, new_node: CSTNode)`.

In many cases, user may want to update an attribute having a non CSTNode value (a str/int literal or sequence) and if it's deep in the tree, we'll need something like this example:
```
# we want to replace the old_value as new_value
node = cst.parse_expression("fn(a = "old_value", b = 2)")
updated_node = node.deep_replace(node.args[0].value, node.args[0].value.with_changes(value="new_value")
# note: we cannot pass node.args[0].value.value to deep_replace since 
# it's a str instead of a CSTNode.
```

If we can have a `.with_deep_changes(old_node: CSTNode, new_node: CSTNode, **changes)` which combines `.with_changes()` and `.deep_replace()`, the code can be really simple:
```
updated_node = node.with_deep_changes(node.args[0].value, value='"new_value"')
```

**Comment by DragonMinded** [comment]
This is now in LibCST and used in a few places across the code. Closing.
