### ISSUE TITLE
Implement PEP 696 (defaults for type params)

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#1127]
https://peps.python.org/pep-0696/#grammar-changes will ship with Python 3.13, so I'd like to get this into LibCST by the time the release candidates for 3.13 are out. Assign to yourself or comment if you start working on it, please.

## Node changes
Seems like the most straightforward way is to extend `statement.TypeParam` to own the equals sign (which owns its surrounding whitespace), and the default value itself.

* The [python version](https://github.com/Instagram/LibCST/blob/9f54920d9d32a519aa1702485ed56c55d8189a0c/libcst/_nodes/statement.py#L3644) needs these extra fields. You can take inspiration from [`expression.Param`](https://github.com/Instagram/LibCST/blob/9f54920d9d32a519aa1702485ed56c55d8189a0c/libcst/_nodes/expression.py#L1778-L1782).
* Also add validation to make sure the equals sign and the default value can only appear together (`expression.Param` also has an example for this)
* We should also add validation in `statement.TypeParameters` to ensure that a `TypeParam` without a default value never follows one with.
* You can exercise the Python code with tests [here](https://github.com/Instagram/LibCST/blob/main/libcst/_nodes/tests/test_type_alias.py).
* The [rust version](https://github.com/Instagram/LibCST/blob/9f54920d9d32a519aa1702485ed56c55d8189a0c/native/libcst/src/nodes/statement.rs#L3476-L3479) needs extending in a similar way.
  * [This part](https://github.com/Instagram/LibCST/blob/main/native/libcst/README.md#nodes) explains various naming conventions and helpers available in Rust for defining nodes.
  * There's no validation for the Rust nodes, and also no `MaybeSentinel` - we use `Option<_>` to signal optional values.
  * I _think_ you won't need to store any actual tokens, so the Rust changes should look equivalent to Python.

## Grammar changes
I recommend reading [this readme](https://github.com/Instagram/LibCST/blob/main/native/libcst/README.md) to get acquainted with the rust bits at a high level.
* The grammar (starts [here](https://github.com/Instagram/LibCST/blob/9f54920d9d32a519aa1702485ed56c55d8189a0c/native/libcst/src/parser/grammar.rs#L91)) needs to be changed following [the PEP](https://peps.python.org/pep-0696/#grammar-changes) as closely as possible. [This is the relevant part](https://github.com/Instagram/LibCST/blob/9f54920d9d32a519aa1702485ed56c55d8189a0c/native/libcst/src/parser/grammar.rs#L794-L797). You can also take a peek at [the cpython grammar changes](https://github.com/python/cpython/pull/116129) (note that the grammar in the PEP seems different than actual CPython grammar - the latter doesn't mention constraints - no idea what's the cause of this, but CPython is the source of truth).
  * The only significant syntactic difference between LibCST and CPython grammar is that LibCST grammar _inlines_ the actions to be taken as a result of a successful parse between `{}` braces in the rule. I try to keep these short, preferably a single function call that's defined later in the file.
  * I _think_ this change won't require any tricks, but of course, feel free to reach out if you get stuck.

## Roundtrip tests

* [this file](https://github.com/Instagram/LibCST/blob/main/native/libcst/tests/fixtures/type_parameters.py) hosts a bunch of type parameter related test cases that aim to exercise edge cases of the syntax.
  * The entire file is parsed into a Rust CST, then codegenned back to source code, to be compared with the original source byte-by-byte. Then the same thing is done using the Python CST (this also exercises validation).
  * Feel free to go crazy with the syntax for new test cases here. These are great ways of catching subtle bugs like whitespace being owned by two nodes simultaneously (thus duplicating it during codegen - make sure there's a case where every possible whitespace is different from the default), inconsistent default values between Python/Rust, too strict validation rules, etc.
* Run them with `cargo test` (the rust roundtrip) or `pytest -k roundtrip` (you might have to `--ignore-glob '*fuzz*'`).

**Comment by JelleZijlstra** [comment]
> * note that the grammar in the PEP seems different than actual CPython grammar - the latter doesn't mention constraints - no idea what's the cause of this, but CPython is the source of truth

The PEP grammar might have been derived from an early version of PEP 695. When I implemented PEP 695 in Python I put the bounds and constraint in the same place in the grammar; they're distinguished later on in the parsing process (if it's a Tuple node, use constraints; otherwise use bound).

**Comment by zsol** [comment]
3.13.0 beta 1 is expected to come out next week. @thereversiblewheel need help? :)

**Comment by zsol** [comment]
I'll try and get a new libcst release while on the pycon sprints now that #1141 has been merged
