### ISSUE TITLE
Accessing .code attribute fails with "TypeError: CSTNode._codegen() missing 1 required positional argument: 'state'"

### ISSUE THREAD

**Issue by ngie-eign** [Instagram/LibCST#1172]
**Note**: All potentially sensitive information has been removed.

## Repro
```
% python libcst_crashes.py
Traceback (most recent call last):
  File "libcst_crashes.py", line 11, in <module>
    output = new_py_module.code
             ^^^^^^^^^^^^^^^^^^
  File "$VENV/lib64/python3.11/site-packages/libcst/_nodes/module.py", line 116, in code
    return self.code_for_node(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "$VENV/lib64/python3.11/site-packages/libcst/_nodes/module.py", line 136, in code_for_node
    node._codegen(state)
  File "$VENV/lib64/python3.11/site-packages/libcst/_nodes/base.py", line 300, in _codegen
    self._codegen_impl(state, **kwargs)
  File "$VENV/lib64/python3.11/site-packages/libcst/_nodes/module.py", line 99, in _codegen_impl
    stmt._codegen(state)
TypeError: CSTNode._codegen() missing 1 required positional argument: 'state'
```
## More details
```
% python -m pip freeze | grep -i cst
libcst==1.4.0
% python -V
Python 3.11.9
```
[libcst_crashes.py.txt](https://github.com/user-attachments/files/16167140/libcst_crashes.py.txt)

**Comment by ngie-eign** [comment]
This was based in part on the [Best Practices doc](https://libcst.readthedocs.io/en/latest/best_practices.html#provide-a-config-when-generating-code-from-templates).

**Comment by ngie-eign** [comment]
Ok, I figured it out.
The core problem was that I used the `libcst.EmptyLine` class instead of creating an instance of `libcst.EmptyLine`. Once I did that and addressed the other issue with directly setting the `.comment` attribute, things just worked.
I can definitely tell that this heat wave/climate change is mucking with my cognitive abilities... *sighs*

**Comment by zsol** [comment]
You can also just `libcst.EmptyLine(comment=libcst.Comment(value="# A new comment"))`
