### ISSUE TITLE
Add a `.code` alternative for all CSTNode subclasses

### ISSUE THREAD

**Issue by bgw** [Instagram/LibCST#16]
Related to the discussion here: https://github.com/Instagram/LibCST/pull/15#pullrequestreview-272641452

`.code` exists on `Module`, but not on other `CSTNode` subclasses.

We can only generate code in the context of a module because the module contains information about the default indentation level, newline, etc.

However it'd be useful to have a `.code` property on every node for debugging purposes. I just don't know how we can communicate these pitfalls to the developer.

I'm thinking we could define an API like this:

```
def code_with_context(self, default_newline: str = "\n", default_indent: str = "    "):
    ...
```

What do people think? Is it obvious enough when reading `node.code_with_context()` that the generated code might not exactly match the code in the original module? Should we use a different name? Is this a bad idea? Should we stick with `Module.code_for_node`?

**Comment by DragonMinded** [comment]
There are some nodes (namely Annotation) that cannot be generated at all, unless they are being generated inside a parent. How do we want to handle those? Do we want to have a `.code` attribute only on nodes that are top-level (AKA where at least one of `parse_statment(node.code)`, `parse_expression(node.code)` or `parse_module(node.code)` won't fail)?

**Comment by bgw** [comment]
@DragonMinded

I'd imagine that they'd either raise an exception (what `Annotation` does now), or just pick some default value for the missing information (e.g. an `Arg` with a sentinel comma just doesn't attach a comment). We should probably be consistent about how we handle it.

Either of these behaviors is no worse than how `Module.code_for_node` handles it.

> Do we want to have a .code attribute only on nodes that are top-level

`Annotation` is the only node I know of that actually fails right now (instead of inserting a dummy value), so I think my preference would be to make it default to `->` or `:` as the indicator, and implement the attribute/method on the `CSTNode` base class. That seems like the easiest way to implement this.

This kind of problem of nodes outputting different code depending on where they are in the tree isn't solvable. Even if you restrict what nodes support `.code`/`.code_with_context`, expressions or statements might still render differently because they don't know the current indentation level.

For that reason, I think we should just pick a name for our attribute or method that indicates that it's not going to be the same, or possibly that it's intended for debugging purposes.

**Comment by DragonMinded** [comment]
This isn't a priority, especially now that we have `self.module.code_for_node` helper attached to Codemods.
