### ISSUE TITLE
Running scope analisys example raises exception

### ISSUE THREAD

**Issue by luismojena** [Instagram/LibCST#166]
Running this example [https://libcst.readthedocs.io/en/latest/scope_tutorial.html](https://libcst.readthedocs.io/en/latest/scope_tutorial.html)
raises the following error when I run it locally:
> Traceback (most recent call last):
>   File "~/bla.py", line 24, in <module>
>     wrapper = cst.metadata.MetadataWrapper(cst.parse_module(source))
> AttributeError: module 'libcst.metadata' has no attribute 'MetadataWrapper'

but it works on the binder notebook. There are also differences in the module structure.

Is the code on `master` turned into a package and pushed to pypi on every successful merge?

**Comment by jimmylai** [comment]
What's the version of LibCST you run? Can you upgrade to new version and try again?
I cannot reproduce your issue on my environment. `MetadataWrapper` is available via `cst.metadata.MetadataWrapper` once `import libcst as cst`.
The pypi package was released manually in roughly every two weeks.

**Comment by luismojena** [comment]
I have version `0.1.3`, after doing `poetry update`, I have the same version and the Exception continues to show up.
