### ISSUE TITLE
[discussion] LibCST based lint framework provides auto fixes

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#177]
LibCST based lint framework can provide the following benefits:
- auto fixes.
- rich information from Metadata API for advanced lint rules.
- flexible patterns to traverse syntax tree: visitor or matcher.

Autofix:
- suggest code changes for developer to accept in one click.
- suggested changes could be wrong and developer can silent them with special comment.

Examples:
- many programming suggestions in PEP8 can be auto-fixed: https://www.python.org/dev/peps/pep-0008/#programming-recommendations
  - `is` rather than `==` when compare to a singleton 
  - `... is not ...` rather than `not ... is ...`

More context: "Lint Fatigue" section in https://instagram-engineering.com/static-analysis-at-scale-an-instagram-story-8f498ab71a0c

**Comment by zsol** [comment]
This is now https://github.com/Instagram/Fixit/
