### ISSUE TITLE
Compatibility with older python syntax

### ISSUE THREAD

**Issue by thatch** [Instagram/LibCST#184]
Because I've noticed a couple of references in other projects' bugs: I'm already working on this and don't anticipate that it will be super difficult.  I will be adding support back to 2.7 (but probably stopping there).  I have future-import parsing working as well, which is necessary for print statements and barry_as_FLUFL handling.

https://github.com/thatch/python-grammar-changes has a hand-compiled list of what changed, but I hope to create snippets and mechanically verify what versions they work on as well.

**Comment by zsol** [comment]
I think supporting Python 2 syntax is more burden than it's worth at this point, so @thatch unless you have a compelling argument for this work, I'd propose closing this issue and dropping #275
