### ISSUE TITLE
Expose add_slots as public API

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#22]
Currently we import add_slots in this way. `from libcst._add_slots import add_slots`
We'll need add_slots when building other frameworks.
Any suggestion on the namespace we should use? E.g. `libcst.common` or just like the other classes with only `libcst`?

**Comment by DragonMinded** [comment]
If we are going to expose this, its probably best to go in `libcst` like the rest of our exports.

**Comment by DragonMinded** [comment]
This is not a priority, and there are known issues with the `@add_slots` decorator. I think its best if we keep this internal.
