### ISSUE TITLE
[question] Extract body of the root functions from module

### ISSUE THREAD

**Issue by grundic** [Instagram/LibCST#251]
Hello,

Recently discovered this project during finding a solution for my problem.
I have a single python file, which contains one or more functions. I'd like to extract only body of those functions for splitting them later to separate files.

1. Could you please review my attempt and suggest any improvements?
2. Also I don't know how to separate nested functions in the visitor: tried to find some property of indentation, but can't locate it. Would be glad if you could help me with that. 

https://repl.it/@Grigory1/splitter

Thank you.

**Comment by jimmylai** [comment]
Your idea is good which implement visit_FunctionDef to collect the body.
Note that the body of FunctionDef is a BaseSuite which can be an IndentedBlock (which should be the most cases.)
https://libcst.readthedocs.io/en/latest/nodes.html#libcst.FunctionDef
https://libcst.readthedocs.io/en/latest/nodes.html#libcst.BaseSuite

When building a Module, the body of module is just a collection of staements.
https://libcst.readthedocs.io/en/latest/nodes.html#libcst.Module
So we can simplify do this to create a new Module and replace the body with the body of function:
```


import libcst as cst
m = cst.parse_module("")
updated_m = m.with_changes(body=func_indented_block.body)
print(updated_m.code) 
```

Nested function is basically an FunctionDef node under another FunctionDef syntax tree. You can detect that by update an attribute as state to keep track whether you entered a FunctionDef.

```
class Visitor(CSTVisitor):
    def __init__(self):
        self.func_cnt = 0

    def visit_FunctionDef(...):
        self.func_cnt += 1
        if self.func_cnt > 1:
            # this is a nested function
        else:
            # this is not a nested function

    def leave_FunctionDef(...):
        self.func_cnt -= 1
```

The other way to detect nested function or class method is to use ScopeProvider metadat.
https://libcst.readthedocs.io/en/latest/metadata.html#scope-metadata

**Comment by grundic** [comment]
Thank you @jimmylai! 👍
Yeah, totally forgot about the `leave` function.
And your solution with `with_changes` is much simpler.
