### ISSUE TITLE
`RemoveImportsVisitor` incorrectly removes imports in `try/except` and `if` blocks

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#258]
Consider the following input:
```
try:
  import a
except Exception:
  import a

a.hello()
```
Calling `libcst.codemod.visitors.RemoveImportsVisitor.remove_unused_import` for the imports in the above file will incorrectly remove them, even though they're referenced later on.

Here's a small test harness to demonstrate:
```
from typing import Tuple

import click
import libcst as cst
from libcst import codemod
from libcst.codemod.visitors import RemoveImportsVisitor


class RemoveUnusedImportsVisitor(codemod.VisitorBasedCodemodCommand):
    def visit_Import(self, node: cst.Import) -> bool:
        RemoveImportsVisitor.remove_unused_import_by_node(self.context, node)
        return False

    def visit_ImportFrom(self, node: cst.ImportFrom) -> bool:
        RemoveImportsVisitor.remove_unused_import_by_node(self.context, node)
        return False


@click.command()
@click.argument("src", nargs=-1, type=click.Path(writable=True))
def main(src: Tuple[str]) -> None:
    files = codemod.gather_files(src)
    context = codemod.CodemodContext()
    transform = RemoveUnusedImportsVisitor(context)
    codemod.parallel_exec_transform_with_prettyprint(transform, files)


if __name__ == "__main__":
    main()
```

**Comment by jimmylai** [comment]
The logic here caused the issue.
https://github.com/Instagram/LibCST/blob/0ff9a6c5b7f2380dfeca4be01644c9d7e9146a30/libcst/codemod/visitors/_remove_imports.py#L320-L322

It removes imports when multiple import assignments are found. Not sure why it's implemented like this initially but it's not safe to do this. Especially the `try: import ... except: import ...` is a common pattern in Python code.

The easiest way to fix it is to fix the logic in `_is_in_use`.

**Comment by jimmylai** [comment]
Now this is fixed. @zsol, would you like to add your remove unused import `VisitorBasedCodemodCommand` implementation? Then we can make it available in the next LibCST release. With that, everyone can use the CLI to run it over any repository: `python3 -m libcst.tool codemod ...`

**Comment by zsol** [comment]
Will do!
