### ISSUE TITLE
Inserting statements into blocks

### ISSUE THREAD

**Issue by willcrichton** [Instagram/LibCST#263]
I need to refactor code in a way that inserts statements into blocks. For example, let's say I want to extract a constant as a variable. That is, go from:

```python
y = 1 + 2
```

Into:

```python
x1 = 1
x2 = 2
y = x1 + x2
```

Using the standard AST library, I can express this as follows using NodeTransformers:

```python
import ast
import astor

class FindNumbers(ast.NodeTransformer):
    def __init__(self):
        self.assgns = []
        self.i = 0
        
    def fresh(self):
        self.i += 1
        return f'x{self.i}'
        
    def visit_Num(self, node):
        var = self.fresh()
        self.assgns.append(ast.Assign(targets=[ast.Name(id=var)], value=node))
        return ast.Name(id=var)

class ExtractNumbers(ast.NodeTransformer):
    def visit_Assign(self, assgn):
        finder = FindNumbers()
        finder.visit(assgn)
        return finder.assgns + [assgn]
    
stmt = ast.parse('y = 1 + 2')
print(astor.to_source(ExtractNumbers().visit(stmt)))
```

One key element of this is that NodeTransformers can return a list of statements, which enables the code above to insert the additional assignments during `visit_Assign`. The relevant code in CPython is here: https://github.com/python/cpython/blob/3.8/Lib/ast.py#L439-L440

As far as I can tell, this is not possible in LibCST. The transformer `leave` methods must return a `CSTNode`, and there are no nodes which can represent a block of statements that aren't indented.

Is there another way to accomplish this task in LibCST? If not, would y'all be open to a PR to add this feature?

**Comment by willcrichton** [comment]
I hacked up a solution that uses metadata combined with a transformer, but it's kind of ugly. 

```python
import libcst as cst

class FindNumbers(cst.BatchableMetadataProvider):
    def __init__(self):
        super().__init__()
        self.assgns = []
        self.i = 0

    def leave_SimpleStatementLine(self, line):
        self.set_metadata(line, self.assgns)
        self.assgns = []

    def leave_Integer(self, integer):
        self.i += 1
        var = f'x{self.i}'
        self.assgns.append(cst.SimpleStatementLine([
            cst.Assign(targets=[cst.AssignTarget(cst.Name(var))], value=integer)]))
        self.set_metadata(integer, cst.Name(var))

class ExtractNumbers(cst.CSTTransformer):
    METADATA_DEPENDENCIES = (FindNumbers, )

    def _handle_block(self, old_node, new_node):
        new_block = []
        for old_stmt, new_stmt in zip(old_node.body, new_node.body):
            new_stmts = self.get_metadata(FindNumbers, old_stmt)
            if new_stmts:
                new_block.extend(new_stmts)
            new_block.append(new_stmt)
        return new_node.with_changes(body=new_block)

    def leave_IndentedBlock(self, old_node, new_node):
        return self._handle_block(old_node, new_node)

    def leave_Module(self, old_node, new_node):
        return self._handle_block(old_node, new_node)

    def leave_Integer(self, old_integer, new_integer):
        var = self.get_metadata(FindNumbers, old_integer)
        if var:
            return var

        return new_integer

                           
stmt = cst.parse_module('y = 1 + 2')
print(cst.MetadataWrapper(stmt).visit(ExtractNumbers()).code)
```

**Comment by jimmylai** [comment]
Correct, the visitor pattern needs to return a node or a sentinel.
There are some helpers to help you replace or remove a node from a tree.
https://libcst.readthedocs.io/en/latest/nodes.html#libcst.CSTNode.deep_replace
However, those still don't make adding new statement easily.

The insertion needs to find the parent nodes (e.g. IndentedBlock, Module) and wrap the expression with SimpleStatementLine.
We need some high level transform helper to handle those boilerplate.
We already provide a couple high level transform helpers in https://libcst.readthedocs.io/en/latest/codemods.html#library-of-transforms
If you're interested in creating a PR, I'm happy to review.
It can be a `AddStatementVisitor` and provides helper functions like
`AddStatementVisitor.insert_before(nodes: List[CSTNode])` inserts a list of CSTNodes as statements before the current statement,
`AddStatementVisitor.insert_after(nodes: List[CSTNode])` inserts a list of CSTNodes as statements after the current statement.

**Comment by thatch** [comment]
Your example is similar to what I would have come up with.  I don't follow why you need two passes though; it should visit the `leave_*` in depth-first order so by the time you get to `IndentedBlock` you should have been able to collect the information on children.

**Comment by willcrichton** [comment]
@jimmylai I don't think I fully understand the Codemod design yet. How would an `AddStatementVisitor` know what the current statement is? 

@thatch that makes sense. I suppose I can manually track metadata in `ExtractNumbers`, although it does feel like I'm re-implementing some of the `Metadataa infrastructure.

**Comment by willcrichton** [comment]
This is what I've come up with so far. It's a CSTTransformer mixin that provides a `insert_statements_before_current` method: https://gist.github.com/willcrichton/e2ff206b2a0f76e33ee4d2f10c2169ed

If y'all want this in LibCST proper, I can clean it up and submit a PR. Otherwise I'll close this and leave the Gist as a reference snippet for the issue.

**Comment by jimmylai** [comment]
@willcrichton, checked your transformer implementation and the idea looks great.
It's a common refactoring operation to add new statements. If you can add it as a `ContextAwareTransformer` helper to be included in our library of transforms, that'll be very useful for lots of developers. https://libcst.readthedocs.io/en/latest/codemods.html#library-of-transforms
Other than `insert_statements_before_current`, `insert_statements_after_current` can also be useful.

Codemod is a library build on top of visitor/transformer to allow running transformers in a codebase in parallel. So implement a `ContextAwareTransformer` is as simple as implement a `CSTTransformer` and it provides a `context` attribute for storing temporary data. You can find examples of reading/writing data to context in `AddImportsVisitor`.
https://github.com/Instagram/LibCST/blob/9f7018902925f6404f4df8a36045c81cb53424b8/libcst/codemod/visitors/_add_imports.py#L101
Let me know if you have any question. I'm more than happy to review your PR.

**Comment by willcrichton** [comment]
@jimmylai thanks for the advice, I will try and submit a PR. One quick question... I followed the instructions in the README to run pyre (added venv site-packages to Pyre search paths). When I run Pyre check, it hangs here:

```
$ pyre check
 ƛ Processed 40904 of 41403 functions [very large number of seconds]
```

Do you know why that might be?

**Comment by jimmylai** [comment]
@willcrichton Looks like your Python env has lots of packages installed, so it took forever for Pyre to analyze them.
Can you follow the step in README to create a clean env and install the minimum dependency?
`python3 -m venv ../libcst-env/`

**Comment by willcrichton** [comment]
Oh, the issue is that I was using virtualenv, not venv. And I guess virtualenv includes a lot more problematic packages? Using venv solved the issue, thank you.
