### ISSUE TITLE
ImportFrom nodes do not reflect relative imports in module value

### ISSUE THREAD

**Issue by nkashy1** [Instagram/LibCST#272]
It seems impossible currently to tell whether an ImportFrom statement is importing relative to the package. The `.`s are getting dropped when the `ImportFrom` node `module` `Name` node is populated.

To reproduce:

Create a package:
```bash
mkdir import_issue
touch import_issue/__init__.py import_issue/cli.py import_issue/greeting.py
```

Make `greeting.py` look like this:
```python
greeting = 'hello world'
```

Make `cli.py` look like this:
```python
from .greeting import greeting
print(greeting)
```

Test that you get the right greeting:
```bash
python -m import_issue.cli
```

Generate CST for `import_issue/cli.py`:
```bash
python -m libtool.cst print import_issue/cli.py
```

This looks like this:
```
Module(
  body=[
    SimpleStatementLine(
      body=[
        ImportFrom(
          module=Name(
            value='greeting',
          ),
          names=[
            ImportAlias(
              name=Name(
                value='greeting',
              ),
            ),
          ],
        ),
      ],
    ),
    SimpleStatementLine(
      body=[
        Expr(
          value=Call(
            func=Name(
              value='print',
            ),
            args=[
              Arg(
                value=Name(
                  value='greeting',
                ),
              ),
            ],
          ),
        ),
      ],
    ),
  ],
)
```

If you modify `import_issue/cli.py` to look like this (not follow relative import), you get the exact same CST:
```python
from greeting import greeting
print(greeting)
```

**Comment by nkashy1** [comment]
This means that the CST `code` is incorrectly generated when the import is relative.

**Comment by nkashy1** [comment]
Dug a little deeper and I see that the `ImportFrom` node has a `relative` member that should get populated on the kind of statement that I had in `import_issue/cli.py` (as per this test: https://github.com/Instagram/LibCST/blob/master/libcst/_nodes/tests/test_import.py#L402).

It seems that it is not being populated when we produce a CST for the given file, though.

**Comment by nkashy1** [comment]
Should look at `ImportFromParseTest` instead of `ImportFromCreateTest`: https://github.com/Instagram/LibCST/blob/master/libcst/_nodes/tests/test_import.py#L562

**Comment by nkashy1** [comment]
Turns out the unexpected behaviour is in `libcst.tool.dump` - if I set `--show-syntax` then I get the expected output.

Closing the issue. Sorry to have bothered you.

**Comment by jimmylai** [comment]
Yes, you got it right, the dot is preserved in `relative` field.
Glad you figure it out.
Feel free to provide feedback if you have any more!
