### ISSUE TITLE
`ScopeProvider` breaks on accessing an attribute returned by a function.

### ISSUE THREAD

**Issue by rowillia** [Instagram/LibCST#286]
@zsol I'm pretty sure https://github.com/Instagram/LibCST/commit/477a03e3a822fe9b87ef8d891351192325837818 broke this - it worked the commit before that.

Repro:
```python
import libcst as cst

wrapper = cst.metadata.MetadataWrapper(cst.parse_module('foo().bar'))
scopes = set(wrapper.resolve(cst.metadata.ScopeProvider).values())
```

Result:
```
ValueError: Unexpected name value in import: Call(
    func=Name(
        value='super',
        lpar=[],
        rpar=[],
    ),
    args=[],
    lpar=[],
    rpar=[],
    whitespace_after_func=SimpleWhitespace(
        value='',
    ),
    whitespace_before_args=SimpleWhitespace(
        value='',
    ),
)
```

**Comment by jimmylai** [comment]
Thanks for reporting this and included a simple reproduce.
We'll make sure fixing it before releasing the next version.

**Comment by jimmylai** [comment]
Based on the example, the Unexpected name should be `Name(value="foo")` instead of `Name(value="super")`.

**Comment by zsol** [comment]
Apologies, I completely missed this. There's a fix up now.
