### ISSUE TITLE
Position of cst.NotEqual operator includes whitespace

### ISSUE THREAD

**Issue by mallamanis** [Instagram/LibCST#315]
When using the `PositionProvider` the `CodeRange` for `cst.NotEqual` nodes includes the whitespace.

I suspect that this is because [`_codegen_impl`](https://github.com/Instagram/LibCST/blob/5992a7d83d234e7575ad81107d352846ff1abb37/libcst/_nodes/op.py#L705) should instead be
```python
    def _codegen_impl(self, state: CodegenState) -> None:
        self.whitespace_before._codegen(state)
        with state.record_syntactic_position(self):
            state.add_token(self.value)
        self.whitespace_after._codegen(state)
```

**Comment by jimmylai** [comment]
@mallamanis, thanks for reporting the issue. The fix is merged and will be included in the next release 0.3.8.
