### ISSUE TITLE
Apply class method / attribute annotations from the base class to subclasses

### ISSUE THREAD

**Issue by mkurnikov** [Instagram/LibCST#322]
I'm trying to make a script which merges `django-stubs` stubs into the django source code. 

Django inheritance chains could be quite big, so stubs are written in the way that some inherited (abstract or not) methods are defined only in the base class. 

See for example, 
```
class BaseConstraint:
    name: str
    def __init__(self, name: str) -> None: ...
    def constraint_sql(
        self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]
    ) -> str: ...
    def create_sql(self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]) -> str: ...
    def remove_sql(self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]) -> str: ...

class CheckConstraint(BaseConstraint):
    check: Q
    def __init__(self, *, check: Q, name: str) -> None: ...
```

and implementation with applied stubs is 
```
class BaseConstraint:
    def __init__(self, name: str) -> None:
        self.name = name

    def constraint_sql(self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]) -> str:
        raise NotImplementedError('This method must be implemented by a subclass.')

    def create_sql(self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]) -> str:
        raise NotImplementedError('This method must be implemented by a subclass.')

    def remove_sql(self, model: Optional[Type[Model]], schema_editor: Optional[BaseDatabaseSchemaEditor]) -> str:
        raise NotImplementedError('This method must be implemented by a subclass.')

class CheckConstraint(BaseConstraint):
    def __init__(self, *, check: Q, name: str) -> None:
        self.check = check
        super().__init__(name)

    def constraint_sql(self, model, schema_editor):
        check = self._get_check_sql(model, schema_editor)
        return schema_editor._check_sql(self.name, check)

    def create_sql(self, model, schema_editor):
        check = self._get_check_sql(model, schema_editor)
        return schema_editor._create_check_sql(model, self.name, check)

    def remove_sql(self, model, schema_editor):
        return schema_editor._delete_check_sql(model, self.name)
```

I'd like `name: str` and annotations for the `create_sql`, `remove_sql` to be applied to the subclasses too.

**Comment by carljm** [comment]
This is really pretty much unrelated to MonkeyType, which only really creates stubs; the stub-application code is actually not in MonkeyType at all, it's in LibCST. For the sake of modularity and focused tools, I think the best strategy for you here would be to write your own LibCST transformation to create these subclass methods in the source stubs, and then apply that as a prior step to running application.

For your task you shouldn't involve MonkeyType at all, just the apply-stubs transformation in LibCST that MonkeyType calls out to.

**Comment by mkurnikov** [comment]
But it's LibCST repo, no? We're not using MonkeyType since 2018 when I created the first iteration of stubs.

**Comment by carljm** [comment]
Lol, sorry, clearly i somehow thought this was on the MonkeyType repo when I replied. My bad :)

Basically though my thoughts on it remain the same. I don’t think this should be built in behavior of the apply-annotations visitor, which should continue to do its single job well: apply exactly the annotations found in a stub to the marching source. 

What you want to do should be written as a separate LibCST transform, to be run on the stubs before application to the source. I doubt that it’s widely needed enough to be included in the LibCST repo, but LibCST is a great tool for writing it!
