### ISSUE TITLE
Scope metadata not available for some nodes

### ISSUE THREAD

**Issue by lrjball** [Instagram/LibCST#329]
I have been using the `ScopeProvider` to get scopes of various `Name` nodes in some source code, and it seems like some of them are missing from the metadata. In particular, the scope for a function name is in the metadata, but the scope for a class name is not:

```python
import libcst as cst
from libcst.metadata import ScopeProvider


class ScopeVisitor(cst.CSTVisitor):
    METADATA_DEPENDENCIES = (ScopeProvider,)

    def visit_Name(self, node):
        print(node.value, ':')
        try:
            print(self.get_metadata(ScopeProvider, node))
        except KeyError:
            print(f'Failed for {node.value}')


source = """
class Cls:
    pass

def func():
    pass
"""
wrapper = cst.MetadataWrapper(cst.parse_module(source))
wrapper.resolve(ScopeProvider)
result = wrapper.visit(ScopeVisitor())
```

Output:
```
Cls :
Failed for Cls
func :
<libcst.metadata.scope_provider.GlobalScope object at 0x7fc16d7e9898>
```

Expected Output:
```
Cls :
<libcst.metadata.scope_provider.GlobalScope object at 0x7fc16d7e9898>
func :
<libcst.metadata.scope_provider.GlobalScope object at 0x7fc16d7e9898>
```

Do you know why there isn't any metadata available for `Cls`, when there is for `func`?

**Comment by jimmylai** [comment]
If you apply `get_metadata` on the `ClassDef` node, you'll get the expected `GlobalScope` object.
The inconsistency comes from the implementation difference.
https://github.com/Instagram/LibCST/blob/master/libcst/metadata/scope_provider.py#L695-L697

https://github.com/Instagram/LibCST/blob/master/libcst/metadata/scope_provider.py#L734-L736
Add `self.provider.set_metadata(node.name, self.scope)` can keep them consistent.

Feel free to propose pull request to fix it. 
Tests can be added to https://github.com/Instagram/LibCST/blob/master/libcst/metadata/tests/test_scope_provider.py#L229-L285

**Comment by jimmylai** [comment]
The fix will be available in the next LibCST release.

**Comment by lrjball** [comment]
Awesome, thank you!
