### ISSUE TITLE
Specify minimum versions for each dependency

### ISSUE THREAD

**Issue by Zac-HD** [Instagram/LibCST#33]
I've been using `libCST` in [Hypothesmith](https://github.com/Zac-HD/hypothesmith) to generate source code, which has been lots of fun.  (let me know if you're interested in bug reports, or how stable tests need to be before you'd want a PR)

It turns out that one of my environments had `parso==0.2` already installed, and while `pip install libcst` worked fine Parso 0.2 is not actually compatible.  Can I suggest specifying a minimum version of all your dependencies, and adding a test env that checks they're all still supported?

**Comment by jimmylai** [comment]
@Zac-HD Thank you for your feedback. Currently we use both setup.py and requirements.txt files for dependency management. The version requirement is in requirements.txt but not in setup.py.
I'll submit a PR to fix this.

**Comment by jimmylai** [comment]
Added the minimum dependency version number in #38 .

**Comment by jimmylai** [comment]
#38 is merged. @DragonMinded can you release a new version LibCST, so users have old parso, typing_extensions or typing_inspect installed can get the right dependency packages when installing LibCST?

**Comment by bgw** [comment]
> let me know if you're interested in bug reports

Yes! We'd love bug reports. We considered writing a fuzzer, but never got around to it.

> or how stable tests need to be before you'd want a PR

I'm not sure what this means, but we'd welcome an issue if you don't want to write a PR to fix it (though we love PRs!).

**Comment by Zac-HD** [comment]
I mean "I have a fuzzer, but it's currently pre-alpha" - https://pypi.org/project/hypothesmith/

I can write you some fuzz tests easily enough 😁

**Comment by jimmylai** [comment]
The dependency issue was resolved. Closing it now. For fuzzer discussion, we can follow up in #39

**Comment by DragonMinded** [comment]
Version 0.1.1 has been released including the dependency fixes.
