### ISSUE TITLE
Unable to generate code from the node in visitor

### ISSUE THREAD

**Issue by Nomiluks** [Instagram/LibCST#333]
I am searching for a way to get code from the node in the visitor.
Example:

```
import libcst

code_example = """
from ast import parse
threshold  =  1
print(threshold)
"""

class CodeVisitor(libcst.CSTVisitor):
    def visit_Assign(self, node: libcst.Assign) -> bool:
        print(node)
        return True


demo = libcst.parse_module(code_example)
demo.visit(CodeVisitor())

```

In the above code I want to get the code(i.e.  threshold  =  1) of the node . But it seems like libcst doesn't provide that support. I further looked around and figured out a function name `code_for_node(node: libcst._nodes.base.CSTNode) → str` [libcst.Module.code_for_node](https://libcst.readthedocs.io/en/latest/nodes.html#libcst.Module.code_for_node) which belongs to the  **Module** . But I didn't able to find enough help to use this in my code. 

Looking forward for the help. 
Thanks in advance!

**Comment by jimmylai** [comment]
If you search the codebase, you can find some example of `code_for_node()`.

https://github.com/Instagram/LibCST/blob/c023fa7c4caff3fd2b3946080f9a58b539b10363/libcst/_nodes/tests/base.py#L191

We didn't see many use cases need the code of a node, so the `code_for_node` is only build on Module.

**Comment by Nomiluks** [comment]
@jimmylai thanks for your answer. I have figured that out and also posted on StackOverflow for other users: https://stackoverflow.com/questions/62771691/python-libcst-unable-to-generate-code-from-the-node-in-visitor-class

**Comment by jimmylai** [comment]
Add the Q&A to stackoverflow is a great idea!

Closing this issue now.
