### ISSUE TITLE
Removal of future imports

### ISSUE THREAD

**Issue by bgerrity** [Instagram/LibCST#344]
I was running the `remove_unused_imports.RemoveUnusedImportsCommand` codemod and noticed that it stripped my `from __future__ import annotations` import statements (which were being used by forward references in the module).

**Comment by jimmylai** [comment]
@zsol has a fix for this. Target on commit the fix early next week.

**Comment by jimmylai** [comment]
#353 fixed this and it was released in LibCST 0.3.9 last week.
