### ISSUE TITLE
Circular dependency on hypothesmith

### ISSUE THREAD

**Issue by tlc28** [Instagram/LibCST#346]
I'm working on packaging LibCST for Guix (https://guix.gnu.org) and noticed that some LibCST tests were using hypothesmith. The problem is that hypothesis has libcst as a dependency.

Is this on purpose? Can those tests be safely disabled and the dev dependency on hypothesmith dropped in my package?

Thanks

**Comment by jimmylai** [comment]
Hypothesis only runs when env variable `HYPOTHESIS ` is set.
https://github.com/Instagram/LibCST/blob/6a5f71c6b4eebe1f798ecb5c168a5a372fce87a0/tox.ini#L64
It's fuzz tests to discover code patterns cannot be parsed by LibCST. They are not needed at runtime. So not include them is fine.

**Comment by tlc28** [comment]
Hi @jimmylai ! Thanks for your answer!

I've just realized that I misspelled the second "hypothesmith" and wrote "hypothesis"! My bad!

I don't have HYPOTHESIS set in my test environment, so the tests are skipped… but hypothesmith is still imported!

```
======================================================================
ERROR: libcst.tests.test_fuzz (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: libcst.tests.test_fuzz
Traceback (most recent call last):
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/guix-build-python-libcst-0.3.7.drv-0/libcst-0.3.7/libcst/tests/test_fuzz.py", line 19, in <module>
    from hypothesmith import from_grammar
ModuleNotFoundError: No module named 'hypothesmith'
```

I cannot import it, because hypothesmith as a dependency on libcst [1][], which I'm trying to package. Hence the circular dependency.

[1]: https://github.com/Zac-HD/hypothesmith/blob/master/setup.py#L35

So I guess I'll just disable this test.

**Comment by carljm** [comment]
It should be fine to just remove `test_fuzz.py` from your distribution altogether if needed. Thanks for the report!
