### ISSUE TITLE
ScopeProvider sometimes returns nodes that don't appear in the CST

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#381]
Consider this example code:
```
def f() -> "None":
  pass
```

Scope analysis will return an `Access` for a node like `Name(value="None")`, but there's no such CST node in the code. This is a problem because users of LibCST would expect to query metadata (for example the position) of nodes returned by scope analysis.

Here's some code to demonstrate the problem:

```
import libcst as cst
m = cst.metadata.MetadataWrapper(cst.parse_module("def f() -> \"None\": pass"))
pos = m.resolve(cst.metadata.PositionProvider)
global_scope = list(filter(None, m.resolve(cst.metadata.ScopeProvider).values()))[0]
alien_node = list(global_scope.accesses['None'])[0].node
pos[alien_node]  # BOOM
```

This produces an exception like the following:
```
KeyError: Name(
    value='None',
    lpar=[],
    rpar=[],
)
```

**Comment by zsol** [comment]
I suspect the issue exists since #373, where we construct a new CST for each string annotation, and then nodes from this constructed CST are exposed by `ScopeProvider`. I _think_ we should instead expose the original string annotation CST nodes as the referrer nodes.

**Comment by jimmylai** [comment]
> I suspect the issue exists since #373, where we construct a new CST for each string annotation, and then nodes from this constructed CST are exposed by `ScopeProvider`. I _think_ we should instead expose the original string annotation CST nodes as the referrer nodes.

Nice catch! The change does expose new CSTNode which not existed in the original node.

The suggestion makes sense for simple type annotation with a type name.

For the case that the String is an expression with multiple parts, is exposing the entire string annotation still useful?
E.g. `a: "Optional[A, B]" = None`

**Comment by zsol** [comment]
I think it's still better than nothing. Not to mention it would be great to keep the `Access.node` attribute as not `Optional`
