### ISSUE TITLE
A simple command-line interface

### ISSUE THREAD

**Issue by isidentical** [Instagram/LibCST#383]
The `ast` module (starting from 3.9) has a simple command line interface that is extremely useful while debugging / building something with the AST.
```
 $ python -m ast
2 + 2
Module(
   body=[
      Expr(
         value=BinOp(
            left=Constant(value=2),
            op=Add(),
            right=Constant(value=2)))],
   type_ignores=[])
```
IMHO it would be awesome to have such a thing in LibCST as well. If agreed upon the idea, I can supply a patch!

**Comment by zsol** [comment]
This already exists, you can do `python -m libcst.tool print somefile.py`

**Comment by isidentical** [comment]
Oh, wasn't aware of that. Thanks!
