### ISSUE TITLE
Bowler integration

### ISSUE THREAD

**Issue by ulziibay** [Instagram/LibCST#40]
[Bowler](https://pybowler.io/) provides nice API and CLI over writing codemods. However, Bowler uses the `lib2to3` CST format, which you claim is complex and "[makes it hard to extract the semantics we care about.](https://instagram-engineering.com/static-analysis-at-scale-an-instagram-story-8f498ab71a0c
)" 
However, Bowler is useful in that it provide it provides a CLI interface, which make is very easy to use in CI/CD environments. 
Is there any plan to integrate libCST with Bowler? If so, when?

**Comment by jreese** [comment]
Yes, there is a desire to migrate Bowler to LibCST, but it will be complicated, and there is not an ETA at the moment.  As of right now, LibCST does not support versions of Python older than 3.6/3.7, while lib2to3/Bowler supports code in a transitional 2.7/3.x format.  The LibCST matcher is also not a direct analog of the systems from lib2to3, so we would need to find or build alternatives for the selector syntax and fixers that can sit on top of LibCST.  This will likely represent a "Bowler 2.0" level of change to the framework.

If you're interested in helping with these components, feel free to file an issue on Bowler for the transition, and we can help with defining the pieces that need to be built out.

**Comment by carljm** [comment]
Closing this issue since it's not actionable for LibCST, but rather for Bowler. If there are specific LibCST issues blocking Bowler integration they should be filed separately.
