### ISSUE TITLE
Unclear if code ranges are inclusive or exclusive

### ISSUE THREAD

**Issue by arxanas** [Instagram/LibCST#42]
https://libcst.readthedocs.io/en/latest/metadata.html#libcst.CodeRange specifies this:

```
class libcst.CodeRange
  start : CodePosition
    Starting position of a node.

  end : CodePosition
    Ending position of a node.
```

It's not clear from this documentation whether the `end` position should be considered to be part of the node, or if it indicates one-past-the-last-character of the node. The documentation should specify this.

**Comment by bgw** [comment]
Thanks for the feedback, @arxanas.
