### ISSUE TITLE
`parse_module("not+1")` raises an error

### ISSUE THREAD

**Issue by Zac-HD** [Instagram/LibCST#44]
But it *is* valid Python, which evaluates to `False`.

Of course the fuzzer didn't find this on my machine or in CI for the pull request, but [after merging](https://circleci.com/gh/Instagram/LibCST/1637) :roll_eyes:

**Comment by DragonMinded** [comment]
This should be addressed by https://github.com/Instagram/LibCST/pull/43

I think there's other cases where we aren't correctly recursively evaluating spacing requirements, but that should get a large chunk of cases (and gets all of the ones found so far by the fuzzer). I want to run the fuzzer for a lot longer locally and continue to flush out issues like this.

**Comment by DragonMinded** [comment]
After landing #43 I can successfully parse this via LibCST.
