### ISSUE TITLE
How to use with_deep_changes

### ISSUE THREAD

**Issue by tsoernes** [Instagram/LibCST#444]
Let's say i've got a node `line_node`
```
ipdb> line_node
SimpleStatementLine(
    body=[
        Expr(
            value=Call(
.....
            ),
            semicolon=MaybeSentinel.DEFAULT,
        ),
    ],
    leading_lines=[],
    trailing_whitespace=TrailingWhitespace(
        whitespace=SimpleWhitespace(
            value='  ',
        ),
        comment=Comment(
            value='# yapf: disable',
        ),
        newline=Newline(
            value=None,
        ),
    ),
)
```
And a replacement node of type Call. How do I replace it? The body > Expr > value

**Comment by jimmylai** [comment]
`with_deep_changes()` take an `old_node` and changes.
https://libcst.readthedocs.io/en/latest/nodes.html?highlight=with_deep_changes#libcst.CSTNode.with_deep_changes

To replace the value of Expr with a `new_value`: `line_node(expr_node, value=new_value)`
(`expr_node = line_node.body[0]`)

**Comment by tsoernes** [comment]
Perfect, thanks a bunch.
