### ISSUE TITLE
TypeInferenceProvider raises if empty cache is provided

### ISSUE THREAD

**Issue by lisroach** [Instagram/LibCST#475]
Per: https://github.com/Instagram/Fixit/pull/31#discussion_r452948963

`TypeInferenceProvider` raises when `cache` is `{}`.

Fixing this bug will allow us to remove the [PLACEHOLDER_CACHES](https://github.com/Instagram/Fixit/blob/1f11c185c0541d419ada74fb938f4ac78f122971/fixit/common/full_repo_metadata.py#L23) and neaten up the code in Fixit.

**Comment by mir-am** [comment]
In my code, I managed to fix the `TypeInferenceProvider ` breakage by passing `{'types':[]}` to `cache` .
Thanks for fixing the issue.

**Comment by lisroach** [comment]
> In my code, I managed to fix the `TypeInferenceProvider ` breakage by passing `{'types':[]}` to `cache` .

That's what I've been doing too, this fix should make for some cleaner code now :)
