### ISSUE TITLE
Where can I find line number information in each CSTNode?

### ISSUE THREAD

**Issue by sangwoo-joh** [Instagram/LibCST#481]
While I was reading [Nodes documentation](https://libcst.readthedocs.io/en/latest/nodes.html), I couldn't find any information regarding the line number attached to each node.

Where can I find the line number information attached in each `CSTNode`?
For example, `lineno` may be the line number that the node's span starts from, and `end_lineno` be the line number that the node's span ends, just like [ast](https://docs.python.org/ko/3/library/ast.html).

**Comment by thatch** [comment]
This is provided using the metadata system. See https://libcst.readthedocs.io/en/latest/metadata.html#libcst.metadata.PositionProvider and a tutorial at https://libcst.readthedocs.io/en/latest/metadata_tutorial.html#Accessing-Metadata

**Comment by sangwoo-joh** [comment]
@thatch Thank you very much!!
