### ISSUE TITLE
ScopeProvider fails when string type annotation is unparseable

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#491]
Example:
```
src = 'a: "{hello{foo}}"'
cst.MetadataWrapper(cst.parse_module(src)).resolve(cst.metadata.ScopeProvider)
```

**Comment by zsol** [comment]
ScopeProvider should fail gracefully in these cases. It's probably enough to catch the exception from the internal `parse_expression` call during `_handle_string_annotation`.

**Comment by srisatya1197** [comment]
@zsol will work on this issue.

**Comment by zsol** [comment]
Great, thank you!

**Comment by srisatya1197** [comment]
@zsol Are there any contributing guidleines, Like do I have to install any packages or tools?

**Comment by zsol** [comment]
Check out [the readme](https://github.com/Instagram/LibCST/blob/master/README.rst#development) and [CONTRIBUTING.md](https://github.com/Instagram/LibCST/blob/master/CONTRIBUTING.md)

**Comment by srisatya1197** [comment]
Thank you so much.

**Comment by zzl0** [comment]
@zsol I was trying to find some "good first issue", it seems this issue has already been fixed by @lpetre .

**Comment by zsol** [comment]
That's right, thanks for the heads up :)
