### ISSUE TITLE
how to update/add docstrings 

### ISSUE THREAD

**Issue by Josverl** [Instagram/LibCST#493]
hello Newby CTS user here.

i've been trying to find a way to add / update docstrings of modules, classes and functions/methods with additional information.
i have not been able to find a way to do this.
there is `get_docstring`, and I have been trying the re-implement that logic in order to to get something working , but im not sure how to approach this.
- using visitors and transformers works well for a lot , but does not allow updating of docstrings (afaik) 
- is this(adding/updating docstrings)  possible using a codemodding , or will that run into the same issue in a different wrapper ?

**Comment by zsol** [comment]
You can match on functions/classes and if their body's first `SimpleStatementLine` is a string, you can manipulate that.
