### ISSUE TITLE
Codemodding fails on windows due to error calling black with env={}

### ISSUE THREAD

**Issue by Josverl** [Instagram/LibCST#494]
# The issue: 

- when running any codemod on windows 10, the codemod itself is run successfully, 
- but the black formatting cannot be run due to `env={}` arguments in the code
- Note : this is also not reported as an warning or error, but as a success (`Finished codemodding 1 files!`)

## simple example of the issue

```
(.venv) PS C:\develop\MyPython\LibCST> black.exe
No Path provided. Nothing to do 😴
(.venv) PS C:\develop\MyPython\LibCST> python -m libcst.tool codemod convert_format_to_fstring.ConvertFormatStringCommand .\stubbertest\testfile.py
Calculating full-repo metadata...
Executing codemod...
Codemodding C:\develop\MyPython\LibCST\stubbertest\testfile.py
Traceback (most recent call last):
  File "C:\develop\MyPython\LibCST\libcst\codemod\_cli.py", line 327, in _execute_transform
    newcode = invoke_formatter(config.formatter_args, newcode)
  File "C:\develop\MyPython\LibCST\libcst\codemod\_cli.py", line 56, in invoke_formatter
    subprocess.check_output(
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect

Failed to codemod C:\develop\MyPython\LibCST\stubbertest\testfile.py

Finished codemodding 1 files!
 - Transformed 0 files successfully.
 - Skipped 0 files.
 - Failed to codemod 1 files.
 - 0 warnings were generated.
(.venv) PS C:\develop\MyPython\LibCST>

```
# Minimal repo 

``` python
import subprocess

code = """
print("hello {}".format("Jos"))
"""

code = bytes(code, "utf-8")
output = subprocess.check_output(
    ["black", "-"],
    env={},   # <-- if empty : OSError: [WinError 87] The parameter is incorrect
    input=code,
)
print(output)

```

from https://docs.python.org/3/library/subprocess.html#subprocess.check_output :  
If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.
Note If specified, env must provide any variables required for the program to execute. **On Windows, in order to run a side-by-side assembly the specified env must include a valid SystemRoot.**

by omitting the `env={}` , or using `env=None` things work smoothly on Windows 10

## System info
OS: Windows_NT x64 10.0.19043
Python 3.9.5 (.venv)
libcst  0.3.19
black, version 21.6b0

**Comment by zsol** [comment]
Thanks for reporting! This line can be removed: https://github.com/Instagram/LibCST/blob/e759ca8290585cf3badcd22ac5e1fdbc5e4f9e13/libcst/codemod/_cli.py#L58

Happy to accept a PR.
I'm curious, have you had any other issues running LibCST on Windows? It's not really a supported platform at the moment, but it would be good to know if there are any blockers apart from this.

**Comment by Josverl** [comment]
@zsol , 
I was already working on the PR , and set it to `env=None` under the assumption that there must have been a reason for that line on other platforms.
Happy to remove it if you confirm that makes sense.

I did not see support platforms listed, other than Python >= 3.6, and I like the functionality offered, but am really just getting started with this.  my intended goal is to develop on Windows native and Windows WLS and run in CI/CD on Ubuntu, so I'll keep my eyes peeled for differences and raise an issue if I suspect a bug.
