### ISSUE TITLE
Unable to remove call

### ISSUE THREAD

**Issue by richtier** [Instagram/LibCST#534]
I am trying to remove an entire line. Specifically, a function call. I get the following error though:

```
TypeError: We got a RemovalSentinel while visiting a Call. This node's parent does not allow it to be removed.
```

Say I want to delete `foo.bar()`

I have tried nice and simple:

```py
class Transformer(CSTTransformer):
    def visit_Call(self, original_node, updated_node):
        if m.matches(node, m.Call(func=m.Attribute(value=m.Name("foo"), attr=m.Name("bar")))):
            return cst.RemoveFromParent()


cst.parse_module(source).visit(Transformer()).code

```

and more complex approach of adding the nodes to be removed to a list, then calling `deep_remove` in `leave_Module`

```py
class Transformer(CSTTransformer):
    def __init__(self, *args, **kwargs):
        self.to_remove = []
        super().__init__(*args, **kwargs)

    def visit_Call(self, node: cst.Call) -> None:
        if m.matches(node, m.Call(func=m.Attribute(value=m.Name("foo"), attr=m.Name("bar")))):
            self.to_remove.append(node)

    def leave_Module(self, node: cst.Module):
        for child in self.to_remove:
             return node.deep_remove(child)

cst.parse_module(source).visit(Transformer()).code

```

But keep getting this error.

I suspect removing a line should be simple and I'm doing something wrong

**Comment by thatch** [comment]
Are you trying to remove statements that are Call, or where it's used as a value?  To advise better, can you provide a sample use you're trying to erase?

**Comment by richtier** [comment]
thanks for the help :)

I am trying to remove statements that are Call-ing `foo.bar()`

for example:

```import foo

def some_function():
    foo.bar()  # Remove this line entirely.
    return True
```

**Comment by richtier** [comment]
for now will use lower tech solution
