### ISSUE TITLE
Add a py.typed file

### ISSUE THREAD

**Issue by zhammer** [Instagram/LibCST#57]
Can you add a `py.typed` file (https://www.python.org/dev/peps/pep-0561/) for libcst? Without it I can't use the libcst types in my `mypy` typechecking when importing the package.

I understand if you're not ready to export the type definitions yet. Also, given I haven't used `pyre` before, maybe `pyre` doesn't require a `py.typed` file for exporting types?

Here's my error log from mypy:
```
Zachs-MBP:tornado-async-transformer zhammer$ mypy tornado_async_transformer
tornado_async_transformer/helpers.py:4: error: Cannot find module named 'libcst'
tornado_async_transformer/helpers.py:4: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
tornado_async_transformer/tornado_async_transformer.py:3: error: Cannot find module named 'libcst'
tornado_async_transformer/tool.py:8: error: Cannot find module named 'libcst'
```

**Comment by zhammer** [comment]
Happy to submit a PR if desired

**Comment by jimmylai** [comment]
@zhammer , LibCST currently uses pyre for type check and it's fully typed. 
I'm aware that mypy is a more popular type checker and happy to support it.
I'm new to mypy and had followed the document to add the support with this commit but it didn't work.
https://github.com/jimmylai/LibCST/commit/12f4432ceab212430df8d0c538199b422ddf912e

With the change, `python setup.py sdist` to built a local package file in `dist/libcst-0.1.2.tar.gz`.
Created a new venv to install the package with `pip install dist/libcst-0.1.2.tar.gz` and mypy `pip install mypy`.
Then created a test module `t.py` with one single line `import libcst`.
I got the same error as you (Cannot find module named 'libcst') when I run `mypy t.py`

I got stuck here. I've followed all the instructions and double checked.
If you could help to make it work, I'm happy to merge the change to support mypy.

**Comment by zhammer** [comment]
hmm.. that commit seems like all that should be needed. i'll take a look sometime today.

**Comment by jimmylai** [comment]
@zhammer did you get any luck?

**Comment by zhammer** [comment]
just tried this by installing the egg directly from your git commit and it seemed to work:

```
Zachs-MBP:testdir zhammer$ python3.7 -m virtualenv venv
...
Installing setuptools, pip, wheel...done.
Zachs-MBP:testdir zhammer$ . venv/bin/activate
(venv) Zachs-MBP:testdir zhammer$ pip install git+https://github.com/jimmylai/libcst.git@7a3b224f0b0592e61f59ca8b2ee8db54582c0d45#egg=libcst
...
(venv) Zachs-MBP:testdir zhammer$ ls venv/lib/python3.7/site-packages/libcst/py.typed 
venv/lib/python3.7/site-packages/libcst/py.typed
(venv) Zachs-MBP:testdir zhammer$ pip install mypy
...
(venv) Zachs-MBP:testdir zhammer$ echo "import libcst" > myfile.py
(venv) Zachs-MBP:testdir zhammer$ mypy --strict myfile.py 
(venv) Zachs-MBP:testdir zhammer$ echo $?
0
(venv) Zachs-MBP:testdir zhammer$ pip uninstall libcst
...
  Successfully uninstalled libcst-0.1.2
(venv) Zachs-MBP:testdir zhammer$ mypy --strict myfile.py 
myfile.py:1: error: Cannot find module named 'libcst'
myfile.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

**Comment by zhammer** [comment]
if i have time i'll take a look following your steps sometime this weekend!

**Comment by jimmylai** [comment]
After added the type file to MANIFEST.in, it worked.
More detail is in https://github.com/Instagram/LibCST/pull/64

**Comment by zhammer** [comment]
Ah good find. Forgot about manifest file

**Comment by jimmylai** [comment]
Closing this for now as https://github.com/Instagram/LibCST/pull/64 was merged. It'll be available in the next release.
