### ISSUE TITLE
support relative imports in AddImportsVisitor

### ISSUE THREAD

**Issue by martindemello** [Instagram/LibCST#578]
The definition of an `import` is currently `(module, obj, asname)`, leaving no way to handle relative imports in codemods that use the visitor.

**Comment by martindemello** [comment]
also while looking at this, i feel like the code would be a lot easier to work with if the list of imports were converted from a tuple to a dataclass within the public methods, and then the dataclass was passed around internally. i've noticed that the libcst codebase makes heavy use of tuples as a general style - would a refactoring of this one visitor to use a dataclass be rejected on consistency grounds? if not i'll submit a PR for that first, and then add relative import support on top of it.

**Comment by martindemello** [comment]
forgot to mention that i did find a workaround - manually adding dots to the module name before calling the visitor works, but it would be nicer to have it handle the relative level as part of the method call.

**Comment by zsol** [comment]
I'm in favor of refactoring that particular tuple to dataclasses. Happy to accept a PR for all the issues mentioned here.
