### ISSUE TITLE
Variable name reuse causes unexpected behaving when getting variable accesses via ScopeProvider

### ISSUE THREAD

**Issue by richtier** [Instagram/LibCST#602]
How to handle when a variable has been overwritten in the scope?

```
import libcst

wrapper = libcst.metadata.MetadataWrapper(
    libcst.parse_module(
    '''
f = 'foo'
print(f)

def f():
    pass

f()

f = 2
    '''
    )
)

scope = wrapper.resolve(libcst.metadata.ScopeProvider)
name = wrapper.module.body[-1].body[0].targets[0].target
print(len(scope[name].accesses[name]))  # returns 2, expected 0
```

2 items are returned because there were 2 access to a variable called `f`:

```
print(f)
f()
```

but they are not the "same" `f`. The final `f` overrode the previous ones, so I would expect it to print 0

Is there a way to handle this?

**Comment by zsol** [comment]
Unfortunately figuring out which access to `f` refers to which assignment is out of scope for a simple library like LibCST's scope provider. This problem is more suitable for tools that do proper program analysis, like type checkers.
