### ISSUE TITLE
Bad Build for Apple M1?

### ISSUE THREAD

**Issue by z3dev** [Instagram/LibCST#612]
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Looking in indexes: https://cr-pypicloud-j6xpbe2uja-uc.a.run.app/simple, https://pypi.org/simple
[pipenv.exceptions.InstallError]: Collecting libcst==0.4.0
[pipenv.exceptions.InstallError]:   Using cached libcst-0.4.0.tar.gz (702 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /home/vscode/.local/share/virtualenvs/loader-EVTLydml/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6wsrw308/libcst_edf7bfa12d5a42f08d8e165eb240175e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6wsrw308/libcst_edf7bfa12d5a42f08d8e165eb240175e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d0v8jagc
[pipenv.exceptions.InstallError]:        cwd: /tmp/pip-install-6wsrw308/libcst_edf7bfa12d5a42f08d8e165eb240175e/
[pipenv.exceptions.InstallError]:   Complete output (5 lines):
[pipenv.exceptions.InstallError]:   Traceback (most recent call last):
[pipenv.exceptions.InstallError]:     File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:     File "/tmp/pip-install-6wsrw308/libcst_edf7bfa12d5a42f08d8e165eb240175e/setup.py", line 10, in <module>
[pipenv.exceptions.InstallError]:       from setuptools_rust import Binding, RustExtension
[pipenv.exceptions.InstallError]:   ModuleNotFoundError: No module named 'setuptools_rust'
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]: WARNING: Discarding https://files.pythonhosted.org/packages/3d/f9/6bae4cfd31942b221265ad3df73b3abfb43747897c5161cf3ac5b177cd42/libcst-0.4.0.tar.gz#sha256=cf126117b626fe7da6907ef5e6299fd249282c3db3b3a036895ee80679e1fd39 (from https://pypi.org/simple/libcst/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement libcst==0.4.0 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23, 0.4.0a1, 0.4.0)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for libcst==0.4.0

**Comment by zsol** [comment]
Can you share your python and pip version please?

**Comment by aptalca** [comment]
Did you install rust/cargo?

**Comment by jreese** [comment]
I had a similar issue with a pyenv-installed version of CPython 3.9.3, which resulted in pip deciding to build a wheel locally instead of installing the wheel on PyPI:

```
$ python -VV
Python 3.9.3 (default, May 21 2021, 13:18:43)
[Clang 12.0.5 (clang-1205.0.22.9)]

$ pip -VV
pip 20.2.3 from /Users/jreese/workspace/usort/.venv/lib/python3.9/site-packages/pip (python 3.9)

$ pip install --only-binary :all: libcst==0.4.0
ERROR: Could not find a version that satisfies the requirement libcst==0.4.0 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23)
ERROR: No matching distribution found for libcst==0.4.0
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/jreese/scratch/libcst-rust/venv/bin/python -m pip install --upgrade pip' command.

$ pip --verbose install --only-binary :all: libcst==0.4.0 2>&1 | gh gist create
- Creating gist...
✓ Created gist
https://gist.github.com/992ece2acd21403ab8c8b84471b6f331
```

Looks like this is an issue with older pip versions though. After upgrading pip, the PyPI wheel installs without a problem:

```
pip install -U pip
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-21.3.1

$ pip --verbose install --only-binary :all: libcst==0.4.0
Using pip 21.3.1 from /Users/jreese/scratch/libcst-rust/venv/lib/python3.9/site-packages/pip (python 3.9)
Collecting libcst==0.4.0
  Downloading libcst-0.4.0-cp39-cp39-macosx_11_0_arm64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 3.4 MB/s
Collecting typing-inspect>=0.4.0
  Using cached typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)
Collecting typing-extensions>=3.7.4.2
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting pyyaml>=5.2
  Using cached PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Installing collected packages: typing-extensions, mypy-extensions, typing-inspect, pyyaml, libcst
Successfully installed libcst-0.4.0 mypy-extensions-0.4.3 pyyaml-6.0 typing-extensions-4.0.1 typing-inspect-0.7.1
```

This is probably worth making a note somewhere (readme, docs, PyPI?) specifically mentioning that installing LibCST >= 0.4.0 may require newer versions of pip.
