### ISSUE TITLE
SimpleString.raw_value cannot handle """"foo"""

### ISSUE THREAD

**Issue by richtier** [Instagram/LibCST#636]
A multi-line string can start with a speech mark, but [SimpleString.quote](https://github.com/Instagram/LibCST/blob/c5b073599d9a732bd138b6933a6bf0209ac8e038/libcst/_nodes/expression.py#L648) does not like that and therefore result in `SimpleString.raw_value` raising an exception for perfectly cromulent strings. Take for example these valid strings:

```
>>> """"foo"""  # four "
'"foo'  # evaluates to string starting with one "
```

libcst raises an exception `Invalid string`

These strings are used in the wild. Probably due to typo e.g., [here](https://github.com/ansible/ansible/blob/d19b506ce8c5ee43865b1cead2246fc07cc8902b/lib/ansible/parsing/vault/__init__.py#L761)

**Comment by zzl0** [comment]
@zsol I was looking into this issue and found the bug has already been fixed.

```
$ cat multi_line.py
def foo():
    """"
    foo function
    """
    return 1

$ cat a.py
import sys
import libcst as cst
from libcst.tool import dump

filepath = sys.argv[1]
code = open(filepath).read()

print(dump(cst.parse_module(code)))

$ python a.py multi_line.py
Module(
  body=[
    FunctionDef(
      name=Name(
        value='foo',
      ),
      params=Parameters(),
      body=IndentedBlock(
        body=[
          SimpleStatementLine(
            body=[
              Expr(
                value=SimpleString(
                  value='""""\n    foo function\n    """',
                ),
              ),
            ],
          ),
          SimpleStatementLine(
            body=[
              Return(
                value=Integer(
                  value='1',
                ),
              ),
            ],
          ),
        ],
      ),
    ),
  ],
)
```

**Comment by zzl0** [comment]
@zsol I see, thanks for the quick response and explanation. If no one is working this issue, could I work on it?

**Comment by zsol** [comment]
Absolutely!
