### ISSUE TITLE
Rationale behind "Cannot concatenate parenthesized strings"

### ISSUE THREAD

**Issue by lapplislazuli** [Instagram/LibCST#640]
Hi there, 

I am using LibCST for Code Alternation and add a bunch of strings. 
To be a bit defensive, I added brackets. 
Resulting code goes from 

```Python
some_var: str = "A"
```

to 

```Python
some_var :str = ((("A" + "B") + "C" ) + "D" )
```

I get the following error: 
`libcst._nodes.base.CSTValidationError: Cannot concatenate parenthesized strings.`

Which is a clear message, and I [find it in the code](https://github.com/Instagram/LibCST/blob/bd5ede79533f5279b149d66a8e683161cdf5404c/libcst/_nodes/expression.py#L996), but I don't understand why it exists. 

After all, the code above is correct python code (for both py2 and py3 doing a quick check).

**Comment by zsol** [comment]
Without looking at your code it's hard to tell, but I think you want to use [`BinaryOperation`](https://libcst.readthedocs.io/en/latest/nodes.html#libcst.BinaryOperation) with its `operator` field set to [`Add`](https://libcst.readthedocs.io/en/latest/nodes.html#libcst.Add) instead of [`ConcatenatedString`](https://libcst.readthedocs.io/en/latest/nodes.html#libcst.ConcatenatedString). See the warning in the docs for the latter.

**Comment by lapplislazuli** [comment]
Thanks for the quick answer! 

I basically use one visitor to collect (some) literals, and one transformer to replace them. 
These are my two LibCST Classes that are within a bigger orchestrating class:


```Python
     class __LiteralCollector(cst.CSTVisitor):
        """
        CSTVisitor that collects all literal-values in traversal.
        Any seen value is saved in an according attribute.
        Currently supported types are floats, simple-strings and integers.
        """
        finished = True
        seen_floats = []
        seen_strings = []
        seen_integers = []

        def visit_Float(self, node: "Float") -> Optional[bool]:
            """
            LibCST built-in traversal that puts all seen float-literals in the known literals.
            """
            self.seen_floats.append(node)

        def visit_Integer(self, node: "Integer") -> Optional[bool]:
            [...]

        def visit_SimpleString(self, node: "SimpleString") -> Optional[bool]:
            [...]

    class __Replacer(cst.CSTTransformer):
        """
        The CSTTransformer that traverses the CST and replaces literals with literal+neutral element.
        Currently to cover issues with scoping / identity of literals,
        the first instance of the literal will be altered.
        """

        def __init__(self, to_replace: "CSTNode", replace_type: str):
            self.to_replace = to_replace
            self.replace_type = replace_type
            self.worked = False


        def leave_SimpleString(
                self, original_node: "SimpleString", updated_node: "SimpleString"
        ) -> "BaseExpression":
            """
            LibCST function to traverse simple strings.
            If the simple-string to replace is found, it is replaced by
            > "hey" -> ("hey"+"")
            :param original_node: The node before change
            :param updated_node: The node after (downstream) changes
            :return: the updated node after our changes
            """
            if self.replace_type == "simple_string" \
                    and original_node.deep_equals(self.to_replace) \
                    and not self.worked:
                literal = str(original_node.value)
                replacement = f"({literal}+\"\")"
                expr = cst.parse_expression(replacement)
                updated_node = updated_node.deep_replace(updated_node, expr)
                self.worked = True

                return updated_node
            return updated_node

        def leave_Float(
                self, original_node: "Float", updated_node: "Float"
        ) -> "BaseExpression":
            [... analog to leave_SimpleString... []

        def leave_Integer(
                self, original_node: "Integer", updated_node: "Integer"
        ) -> "BaseExpression":
            """
            [... analog to leave_SimpleString... []
```

If I am not mistaken, the line `expr = cst.parse_expression(replacement)` gives the error. 

The surrounding class just applies them in order, passing the seen values to the transformer. 
At the moment, the class also needs to have a re-try logic.

**Comment by zsol** [comment]
> The following tests fail with libcst 0.4.0:

Right, that's because you're trying to parse statements with `parse_expression`. Try `parse_statement` :)

**Comment by lapplislazuli** [comment]
@zsol thank you, this is absolutely correct. It now works. 

Could there be a warning/error message when doing mistakes like that?

**Comment by zsol** [comment]
The full error message you should get looks like this: https://gist.github.com/zsol/57e0f2053e30a96438ad426f4a623226

Arguably that inner `KeyError` isn't very meaningful to users of the library, but the high level `ParserSyntaxError` should be user-friendly. Do you think it should be improved?

For what it's worth, the (currently opt-in) new parser's exception is a bit simpler: https://gist.github.com/zsol/c68da7eb069b0ae32003c2e67379be47

**Comment by lapplislazuli** [comment]
Hmm, I am not 100% sure. 
I think now that I understand the context (ParserError due to Statement vs. Expression), these error messages make a lot of sense. 
But to understand it, I would need something like
```
ParserError: Failed to parse expression - found statement tokens 
Caused by 
ParserSyntaxError: [...]
```
