### ISSUE TITLE
instagram 2-FA

### ISSUE THREAD

**Issue by hiaselhans** [Instagram/LibCST#658]
Hello,

I know, this really isn't the place to ask, but i am quite desperate now after more than a week trying to reach a human being working at Instagram through many different channels. There is literally no public customer-service at Instagram / Meta so I'd like to reach out here in hope you can direct me to someone...

I think there is something terribly wrong with Instagram's implementation of 2-Factor-Authentication & activation. It opens a big window for account hijacking.
We are affected by it and i heard of a couple of brands facing the same issue.

I think the process can be improved and i would like to get in touch with someone in order to save others from the hassle we are going through. Of course we also want to recover our account.

Thanks for the help!

**Comment by zsol** [comment]
Hi,
You're right, this is definitely not the support forum you're looking for. Unfortunately I can't help you with this problem at all, sorry. None of the current maintainers of this project are working on Instagram.

**Comment by hiaselhans** [comment]
Thanks for your message @zsol 

I know this is not the support forum, but maybe you can help me find out if there actually IS a support forum or technical support from Instagram. It seems you guys are working for the same company and if I was working there i would feel quite embarrassed for that issue and especially for non-existent contact possibilities from my employer.

**Comment by zsol** [comment]
I think your best bet is the company's white hat program: https://www.facebook.com/whitehat/info/
