### ISSUE TITLE
ApplyTypeAnnotationsVisitor: imported symbols should remain qualified when they conflict

### ISSUE THREAD

**Issue by martindemello** [Instagram/LibCST#673]
t.py:
```
def f(x): pass
```
t.pyi:
```
import foo
from bar import A

def f(x: A) -> foo.A: ...
```
merge result:
```
from bar import A
from foo import A

def f(x: A) -> A: pass
```

**Comment by martindemello** [comment]
(working on it)

**Comment by martindemello** [comment]
the simplest solution to this looks like running the type collector twice, once to pick up conflicting imports, and the second time with the existing imports list initialised with the conflicts so that we qualify them. a somewhat more efficient way is to introduce another visitor with just the relevant parts of the type collector copied out, but i'm not sure the performance gain will be worth the extra code.

**Comment by stroxler** [comment]
Does this fix catch the case where there's an existing conflicting import in the code but not the stub?

For example, if the stub is
```
from a import A
```
def foo(x: A) -> None
```

and the code is
```
from b import A

def foo(x):
    y = A()
    y.do_something(x)
```

I'm pretty sure I've seen this case before (the most common situation, which is a little unfortunate, is when `a.A` and `b.A` are actually the same class that has been re-exported, but there's no way to know that for sure without a deeper code analysis than LibCST can do)

**Comment by martindemello** [comment]
good point, i missed that case! will do it in a followup PR.
