### ISSUE TITLE
Bug: positional arguments identifier (`/`) whitespace is not always stored

### ISSUE THREAD

**Issue by onerandomusername** [Instagram/LibCST#679]
### Summary
Whitespace after `/` in a function definition is not persisted.

### Steps to reproduce

This is the processor script that I am using:
```py
import libcst as cst


with open("test.py") as f:
    module = cst.parse_module(f.read())

module = module.visit(cst.CSTTransformer())

with open("write-test.py", "w") as f:
    f.write(module.code)
```

The below code is the code I am testing this on:
```py
class World:
    def say_hello(
        self, user: str, /
    ):
        print('Hello ' + user)
```

Running the above script results in this output:
```py
class World:
    def say_hello(
        self, user: str, /):
        print('Hello ' + user)

```

### Version Info
libcst 0.4.1
python 3.8.10

**Comment by zsol** [comment]
Yep this is a bug in both the old and new parsers (you can test the new one by running your repro script with the `LIBCST_PARSER_TYPE` env var set to `native`)
