### ISSUE TITLE
Please activate the `discussions` tab from the repository settings

### ISSUE THREAD

**Issue by sugatoray** [Instagram/LibCST#683]
Please activate the `discussions` tab from the repository settings. The discusisons tab helps in maintaining a stackoverflow-like Q&A space within the repository itself. It is also easily possible to quickly convert any discussion into an issue (or, vice-versa).

- See here: https://docs.github.com/en/discussions/quickstart

![image](https://user-images.githubusercontent.com/10201242/167303087-8fa8ecd7-d3c7-4f3a-b4c0-188bc8723862.png)

## Note

:arrow_right: I wanted to add the information that `libCST` is also available on conda-forge. 

- feedstock: https://github.com/conda-forge/libcst-feedstock

```sh
conda install -c conda-forge libcst
```

**Comment by sugatoray** [comment]
cc: @zsol

**Comment by zsol** [comment]
I actually wanted to look into this anyway, I think the project would benefit from discussion forums attached to the repo. Unfortunately I don't have the permissions to do it, but I'll raise it with the team that manages these things at Meta.

**Comment by zsol** [comment]
This is now turned on!
