### ISSUE TITLE
Inconsistency and confusion in `FunctionDef.params` and `Call.args`, can we consolidate it?

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#70]
This is a feedback I got during PyCon Taiwan and it make sense to me.

Here are differences:
The FunctionDef.params is a Parameters. Parameters has the following different attributes to categorize different type of Param: params, default_params, start_arg, kwonly_params, star_kwarg, which is a good design. (one thing can be improved here is to rename params as positional_params or position_params which I discussed with @bgw recently)

The Call.args is a list of Arg, each Arg has some attributes like value, keyword (for kw arg), star (for asterisk param). In this pattern, user needs to check each `keyword` attribute to figure out which arg is kw arg. Why not follow the pattern used in Parameter to categorize it as positional_args, kw_args, star_kwarg? That can improve the API consistency and usability. Is there any particular reason we don't want to do it?

**Comment by DragonMinded** [comment]
I remember keeping these separate styles because while function definitions must be done in a particular order, function arguments can appear in a variety of scenarios interleaved with each other. I'm not sure that they can be unified on account of calling conventions in Python.

**Comment by jimmylai** [comment]
Function arguments also have some order convention, e.g. positional args must show before all keyword args.
In the current design, user may need more work in order to analyzing function calls (they need to check attributes of arg to figure out the type of arg and then try to map a Arg to Param). Maybe a helper can make this easier, e.g. given a FunctionDef and a Call, a helper can provide the value of each Param in this Call by analyzing Param and Arg, some of the value may come from Param if it's default_params and missing in Call.

**Comment by DragonMinded** [comment]
Take `func(1, *[2, 3], 4, *[5, 6], **{'a': 7, 'b': 8}, c=9, **{'d': 10})` for example. You can interleave between any of three states (and that is what we do to validate). It is not as simple as putting arguments in the right position, so trying to map a FunctionDef and a Call is not trivially doable (or even possible in some cases) from static analysis.

We did discuss having some operation that, given a FunctionDef node and a Call node, could give you back which Parameters were populated by which Args, but simply constraining the interface will not buy you additional ease of static analysis.

**Comment by DragonMinded** [comment]
Given that above function, any of the kwargs could also be applied to a positional argument that wasn't marked positional only, as long as those arguments showed up after the arguments already applied in the first bit. So, given that an `Arg()` is a keyword argument, it is not at all guaranteed that the function signature will take the argument as a Keyword Argument. So, in fact, pretending to do so by trying to unify will only make the problem worse.

I think that the only realistic way to try to map a set of Args to a set of Params is with a best-effort helper, it is not possible to try to represent by unifying Param and Arg.
