### ISSUE TITLE
Fails to build rust parser

### ISSUE THREAD

**Issue by thatch** [Instagram/LibCST#705]
On commit 6f28c799bb1ce4b0a00ac67b760b6a7ca29f786f (current main)

`pip install -e /path/to/libcst` fails with https://gist.github.com/thatch/ce8386fd7517dcf6af37fd2c65c90e67

These rust errors frighten and confuse me.  Is there a way to list known-working crate versions instead of trusting that semver works, if that's the problem?

**Comment by zsol** [comment]
That's ... interesting. [These versions](https://github.com/Instagram/LibCST/blob/main/native/Cargo.lock) should be working. I'll try repro later today

**Comment by zsol** [comment]
Aha, I think this is going to be the clue: https://gist.github.com/thatch/ce8386fd7517dcf6af37fd2c65c90e67#file-gistfile1-txt-L123

What's your `rustc --version` and `cargo --version`? Seems like really old versions that don't support for example [the minimum required rust version](https://github.com/Instagram/LibCST/blob/main/native/libcst/Cargo.toml#L11) field.

Try and run `rustup update`

**Comment by zsol** [comment]
Feel free to reopen if it still doesn't work, @thatch
