### ISSUE TITLE
Incorrectly triggered "CSTValidationError: Cannot have unbalanced parens"

### ISSUE THREAD

**Issue by MrVPlusOne** [Instagram/LibCST#711]
Hey, 

This error can be triggered as follows:
```python
cst.parse_module("a = (())\n")
```
which causes my application to crash. This was probably introduced in a recent update since it worked fine on "<=0.4.2" but not on ">=0.4.4".

Also I'm parsing with `LIBCST_PARSER_TYPE=native`.

**Comment by zsol** [comment]
Bisect says this regression was introduced in 380f045fe05bfdc6a0555f8e36a0c1c406ca1b77. I'll check it out ASAP
