### ISSUE TITLE
LibCST didn't generate a `tree`, it's a graph which some node can be children of multiple parent nodes

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#72]
Surprisingly, LibCST didn't generate a `tree`, it's a graph which some nodes can be the children of multiple parent nodes.

When I worked on ParentNodeProvider https://github.com/Instagram/LibCST/pull/71, found this issue.

Here is a simple example test case to reproduce the issue. https://github.com/Instagram/LibCST/blob/f4b317501cc749307e5bb560563cde770282f959/libcst/metadata/tests/test_parent_node_provider.py#L49-L77
By using a simple visitor to traverse the node and count the number of visited times by id. One of the node was reused three times as the child node of three different parent nodes.
```
SimpleWhitespace(
    value='',
)
``` 
Test result: https://circleci.com/gh/Instagram/LibCST/2283?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Example source code to be parsed:
```
        foo = 'toplevel'
        fn1(foo)
        fn2(foo)
        def fn_def():
            foo = 'shadow'
            fn3(foo)
```

Due to this issue, I wasn't able to implement the desired ParentNodeProvider because a child not can have multiple nodes as parents but we only expect one. We need this to be fixed to unblock ParentNodeProvider. CC @DragonMinded  @bgw

**Comment by DragonMinded** [comment]
I am unable to duplicate this issue on LibCST master. Don't we make a deep copy of any trees coming in before metadata processing in order to specifically avoid this issue?

**Comment by jimmylai** [comment]
My change was based on current master and it's also reproduced in CI build. The issue was showed case with a CSTVisitor, not a metadata wrapper.

https://github.com/Instagram/LibCST/blob/f4b317501cc749307e5bb560563cde770282f959/libcst/metadata/tests/test_parent_node_provider.py#L49-L77

@DragonMinded will you be able to reproduce it by doing something like this example?

**Comment by DragonMinded** [comment]
I copied that example almost exactly, and was not able to reproduce, but I see what I did wrong and can reproduce now.

**Comment by DragonMinded** [comment]
This looks like a bug with respect to dataclasses default arguments, and in some cases the parser using those defaults instead of substituting its own. For this particular example, we have two `Arg` nodes constructed, one per function call. Both end up using the same `whitespace_after_star` because this is constructed at import time. I think we should take the strategy of always explicitly initializing parameters to dataclasses in the parser, regardless of defaults (the defaults are there because we want ease of construction outside the parser).

**Comment by DragonMinded** [comment]
Okay, I have a fix up for this in the base case in https://github.com/Instagram/LibCST/pull/73

However, I don't think you should be checking for duplicated nodes on parse_module here, given that you are creating a metadata provider. Metadata providers are run post deep_clone which ensures unique nodes. If you want to write such a test that means something for a metadata parser, you should check the `module` inside a `MetadataWrapper`.

**Comment by DragonMinded** [comment]
I think that `deep_clone` is also broken, given that it currently relies on behavior of `_visit_and_replace_children` and some nodes are actually of type `BaseLeaf` which defines its `_visit_and_replace_children` as returning `self`. That means `deep_clone` is not a deep clone.

**Comment by jimmylai** [comment]
Thanks for fixing the bug. With the new added tests, I don't need to test the uniqueness again.
