### ISSUE TITLE
Wheels for python 3.11

### ISSUE THREAD

**Issue by kasium** [Instagram/LibCST#797]
Hello,
since python3.11 is released in a few days, it would be great if you could publish the needed wheels for python 3.11.

Thanks a lot!

**Comment by vfazio** [comment]
> It would be nice to somehow upload 3.11 wheels to the latest version on PyPI. Or publish a new minor version (even without any changes), just to make 3.11 wheels available. Thanks! heart

I may have accidentally broke making wheels for aarch64, a subsequent PR probably needs to be made to fix that.

https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation

**Comment by zsol** [comment]
I'm planning on making a new release soon, which will have the 3.11 wheels. I've been working on fixing aarch64 wheels, which now work (emulation isn't an option unfortunately, the build OOMs on github actions, and is generally really slow anyway)

**Comment by zsol** [comment]
0.4.8 is out now with 3.11 wheels: https://pypi.org/project/libcst/0.4.8
Thanks everyone, enjoy
