### ISSUE TITLE
libcst._version raises ValueError: source code string cannot contain null byte

### ISSUE THREAD

**Issue by kalebdfischer** [Instagram/LibCST#817]
The following is raised when using libcst version 0.4.8 on python 3.9:

```Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/no_implicit_optional.py", line 6, in <module>
    import libcst as cst
  File ".../lib/python3.9/site-packages/libcst/__init__.py", line 215, in <module>
    from libcst._version import version as LIBCST_VERSION
ValueError: source code string cannot contain null byte
```

**Comment by zsol** [comment]
I can't repro this on Windows:
```
❯ python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from libcst._version import version
>>> version
'0.4.8'
```

What platform are you running on? Also, any repro steps?

**Comment by ptpt** [comment]
Reproduced in macOS (M1)

```
❯ uname
Darwin

❯ python3 --version
Python 3.9.6

❯ pip3 install -U --force libcst
Successfully installed libcst-0.4.8 mypy-extensions-0.4.3 pyyaml-6.0 typing-extensions-4.4.0 typing-inspect-0.8.0
```

The source file `_version.py` is a binary file:
```
xxd lib/python3.9/site-packages/libcst/_version.py
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

It works after removing this file.

**Comment by zsol** [comment]
I'm yanking 0.4.8 from pypi until I get a chance to figure this out

**Comment by zsol** [comment]
Looks like `libcst-0.4.8-cp39-cp39-macosx_10_9_x86_64.whl` is the only wheel that's affected. Its size is exactly right, but all bytes are zeroes. It was produced in [this github action run](https://github.com/Instagram/LibCST/actions/runs/3435653877) by cibuildwheel somewhere [here](https://github.com/Instagram/LibCST/actions/runs/3435653877/jobs/5728266791#step:7:2511). I can't tell from the logs what's going wrong here.

Looking at recent (test) wheel artifacts (like [this one](https://github.com/Instagram/LibCST/actions/runs/3435969434)), they're fine.

I'm going to release 0.4.9 now and hope for the best, but this is extremely worrying

**Comment by zsol** [comment]
0.4.9 is released. I verified all `_version.py` files are good. Thanks for the report, and good night :)

**Comment by ptpt** [comment]
thanks for the quick fix!
