### ISSUE TITLE
Lacking support for match statement

### ISSUE THREAD

**Issue by Stercator** [Instagram/LibCST#824]
Context:

- Python 3.10.8
- LibCST 0.4.9

Minimum example:
```
arg = None
match arg:
    case _:
        pass
```
Expectation: parsed without errors

Actual:
```
ParserSyntaxError: Syntax Error @ 2:11.
Incomplete input. Encountered 'arg', but expected ';', or 'NEWLINE'.

    match arg:
          ^
```

**Comment by zsol** [comment]
try setting the `LIBCST_PARSER_TYPE` environment variable to `native` before parsing 3.10+ python files. See https://github.com/Instagram/LibCST/issues/285#issuecomment-1011427731

**Comment by Stercator** [comment]
Perfect! Thank you!
