### ISSUE TITLE
Issue with multi-line format statement

### ISSUE THREAD

**Issue by colin99d** [Instagram/LibCST#846]
I am getting a ParseError for multi-line format statements. The following is my code to get the expression: 
```
pub fn match_expression(expression_text: &str) -> Result<Expression> {
    match libcst_native::parse_expression(expression_text) {
        Ok(expression) => Ok(expression),
        Err(_) => bail!("Failed to extract CST from source"),
    }
}
```
This function can parse the code below just fine:
```
print(
    'foo{0}' 'bar{1}'.format(1, 2)
)
```

However, the function gets a ParseError with the following code:
```
print(
    'foo{0}'
    'bar{1}'.format(1, 2)
)
```

**Comment by charliermarsh** [comment]
This ended up being a user error. In Ruff, we extract the expression source code, and pass it to LibCST to parse. In this case,  we were passing the unparenthesized implicit string concatenation, which on its own isn't a valid expression. (Feel free to close.)

**Comment by zsol** [comment]
Thanks for closing the loop here :)
