### ISSUE TITLE
Changelog is missing entries for 0.4.8 and 0.4.9

### ISSUE THREAD

**Issue by Zac-HD** [Instagram/LibCST#859]
https://pypi.org/project/libcst/ links to https://github.com/Instagram/LibCST/blob/main/CHANGELOG.md which is missing some versions.  What changed?  Do we still need to set `LIBCST_PARSER_TYPE=native` (https://github.com/Instagram/LibCST/issues/285#issuecomment-1011427731, https://github.com/Instagram/LibCST/issues/530#issuecomment-1029492067) ?

**Comment by zsol** [comment]
This is now fixed, sorry for the omission
