### ISSUE TITLE
Implement support for PEP-695

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#922]
There will be:
- [grammar changes](https://peps.python.org/pep-0695/#grammar-changes)
- [scoping changes](https://peps.python.org/pep-0695/#scoping-behavior)
- [CST changes](https://peps.python.org/pep-0695/#ast-changes)

These changes are scheduled to be included in 3.12

**Comment by charliermarsh** [comment]
@zsol - Just for our own internal planning, would you expect / is it a goal for LibCST to support PEP 695 in time for the Python 3.12 release ([2023-10-02](https://peps.python.org/pep-0693/), at time of writing)? Or will it follow after?

**Comment by zsol** [comment]
Yeah I want LibCST to support the latest available CPython release. We'll make it happen.

**Comment by gabriel4k2** [comment]
Really interested in contributing, even on small parts, on this. Is this mainly for maintainers (ie, internally) or are you guys open for contributions?

**Comment by zsol** [comment]
More than happy to accept contributions! Which parts are interesting? Grammar changes are pure Rust, CST are a mix of Python & Rust, scoping changes are pure Python

**Comment by zanieb** [comment]
If helpful, here are the changes in Ruff which includes references to the pyflakes implementation and RustPython parser changes :) https://github.com/astral-sh/ruff/pull/6109

**Comment by zsol** [comment]
#1004 has the grammar and CST changes. Scoping changes seem way more complicated than I anticipated so it won't fit into this weekend :)

**Comment by JelleZijlstra** [comment]
https://jellezijlstra.github.io/pep695 has a lot of discussion of scoping, in case it's helpful.

**Comment by zsol** [comment]
I've got the scoping rules more-or-less implemented in #1014, but I have two questions:

1. (this is about the PEP) How do type parameters on function and class definitions interact with decorators? Intuitively it feels like decorators should wrap the whole class so they should not have visibility into type variables declared on the thing they're decorating - but I haven't found anything specific about this in the PEP or the discussion you mentioned @JelleZijlstra 
2. The way #1014 currently implements the scoping rules, a function's body will have access to the immediately enclosing class's declarations, but only if the function has type parameters. This is obviously incorrect, but I'm not sure how to address this.

**Comment by JelleZijlstra** [comment]
1. Decorators are evaluated outside the annotation scope used for type params, meaning they don't have access to the type params. This is mentioned in the PEP if you search for "decorator". It's also discussed in the docs at https://docs.python.org/3.12/reference/compound_stmts.html#generic-classes

2. Haven't looked at the code, but possibly looking at symtable.c in CPython can inspire a solution.

**Comment by charliermarsh** [comment]
This is awesome -- thank you @zsol! Are you able to publish a new version to crates.io with Python 3.12 support?
