### ISSUE TITLE
pip install -e gets the wrong version number

### ISSUE THREAD

**Issue by martindemello** [Instagram/LibCST#958]
```
$ pip install -e .

ufmt 2.1.0 requires libcst>=0.4.0, but you have libcst 0.1.dev972+g90ce536 which is incompatible.
```

since the current release is `1.0.1` i suspect it was meant to be `1.0.1.dev972etc`, and it's just the first part getting truncated somehow.

**Comment by zsol** [comment]
Maybe you don't have git tags fetched? The default version is 0.1 for setuptools-scm
