### ISSUE TITLE
[low-pri] move CodeRange and CodePosition to under libcst.metadata for consistency.

### ISSUE THREAD

**Issue by jimmylai** [Instagram/LibCST#96]
Move CodeRange and CodePosition to under libcst.metadata for consistency.
We cannot actually move their definition to under libcst.metadata since they were needed in codegen which causing circular dependency. We can export them from libcst.metadata instead of libcst for consistency.

**Comment by DragonMinded** [comment]
This looks to be taken care of by @bgw.
