### ISSUE TITLE
Publishing wheels for musl (alpine 3.17)

### ISSUE THREAD

**Issue by gmile** [Instagram/LibCST#962]
The library can be built on musl with no issues currently. Confirmed by building it using `alpine:3.17` as a base image:

```dockerfile
FROM alpine:3.17 AS build

WORKDIR /tmp

RUN apk add \
  git \
  cargo \
  py-pip

RUN pip3 install \
  setuptools_rust \
  wheel

RUN apk add git cargo py-pip; \
    pip3 install setuptools_rust wheel; \
    git clone --depth 1 --branch v1.0.0 https://github.com/Instagram/LibCST /tmp; \
    cd LibCST; python setup.py bdist_wheel

FROM scratch AS export

COPY --from=build /tmp/dist/libcst-1.0.0-cp310-cp310-linux_x86_64.whl .
```

Could building & publishing a wheel be enbled for musl? 🙏 This would save some hassle for people who just want to install it using `pip` (myself included).

**Comment by zsol** [comment]
Happy to accept a PR!

**Comment by zsol** [comment]
1.5.1 is on the way: https://github.com/Instagram/LibCST/actions/runs/11900399311
