### ISSUE TITLE
Would be great if matchers somehow do automatic `ensure_type`

### ISSUE THREAD

**Issue by kit1980** [Instagram/LibCST#964]
For example, this code:
```
if m.matches(
    step_arg,
    m.Arg(value=m.UnaryOperation(operator=m.Minus(), expression=m.Integer())),
):
    step = -int(step_arg.value.expression.value)
```
Mypy will complain:
error: "BaseExpression" has no attribute "expression"  [attr-defined]

But from the matcher, it clear that `step_arg.value` is a `UnaryOperation`, and `step_arg.value.expression` is `Integer`.

I can satisfy the type checker by changing the last line to this lengthy abomination:
```
     step = -int(cst.ensure_type(cst.ensure_type(step_arg.value, cst.UnaryOperation).expression, cst.Integer).value)
```

**Comment by zsol** [comment]
I don't think this is possible to do with Python's type system :(
